### ISSUE TITLE
list index out of range

### ISSUE THREAD

**Issue by vex-coder** [continue-revolution/sd-webui-segment-anything#8] opened 2023-04-11 08:01 UTC
Traceback (most recent call last):
  File "E:\stable-diffusion-webui_23-02-27_onedrive\python\lib\site-packages\gradio\routes.py", line 337, in run_predict
    output = await app.get_blocks().process_api(
  File "E:\stable-diffusion-webui_23-02-27_onedrive\python\lib\site-packages\gradio\blocks.py", line 1013, in process_api
    inputs = self.preprocess_data(fn_index, inputs, state)
  File "E:\stable-diffusion-webui_23-02-27_onedrive\python\lib\site-packages\gradio\blocks.py", line 911, in preprocess_data
    processed_input.append(block.preprocess(inputs[i]))
IndexError: list index out of range

**Comment by hellojiaru** [comment] 2023-04-11 08:12
same error

**Comment by continue-revolution** [comment] 2023-04-11 08:17
Duplicate of #6

**Closed** 2023-04-11 08:39 UTC
