### ISSUE TITLE
[Bug]: Clicking preview does nothing

### ISSUE THREAD

**Issue by bugxzhu** [continue-revolution/sd-webui-segment-anything#7] opened 2023-04-11 05:51 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

Can upload pictures
Clicking preview does nothing
python version 3.10

in txt2img left click add a black dot, but right click add a black dot too.
in img2img left click and right click both show nothing.

### Steps to reproduce the problem

1. img2img
2. upload image
3. click

### What should have happened?

Clicking preview should show something

### Commit where the problem happens

webui: yes
controlnet:yes 

### What browsers do you use to access the UI ?

Google Chrome

### Command Line Arguments

```Shell
webui.sh --listen --share --xformers --enable-insecure-extension-access --disable-nan-check'
```

### Console logs

```Shell
no information showed about this extension。

stable-diffusion-webui/venv/lib/python3.10/site-packages/gradio/blocks.py", line 911, in preprocess_data
    processed_input.append(block.preprocess(inputs[i]))
IndexError: list index out of range

this is the error about uploading image in img2img box.
```

### Additional information

none

**Comment by ljleb** [comment] 2023-04-11 06:54
IIUC this is a duplicate of #6

**Comment by continue-revolution** [comment] 2023-04-11 08:17
Duplicate of #6

**Closed as completed** 2023-04-11 08:39 UTC
